import React, { useState, useEffect, useRef, useMemo } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../../hooks/useAuth.js";
import {
  Bot,
  Send,
  X,
  Minimize2,
  Maximize2,
  RotateCcw,
  Copy,
  ArrowRight,
  Shield,
  Lightbulb,
  CheckCircle2,
  Sparkles,
  Check,
} from "lucide-react";

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY || "";

/**
 * Call live Gemini 3.6 Flash API with workspace context
 */
const callGeminiAPI = async (userPrompt, pathname, user) => {
  if (!GEMINI_API_KEY) {
    throw new Error("Missing Gemini API Key");
  }

  const role = user?.role || "guest";
  const userName = user?.name || "Workspace Member";
  const companyName = user?.companyName || "TeamFlow Workspace";

  const systemInstruction = `You are FlowAI, a world-class Senior Engineering Lead, Solutions Architect, and workspace copilot built directly into TeamFlow (an enterprise Employee Management System).
User Context:
- Name: ${userName}
- Role: ${role} (Roles are 'admin' or 'employee' or 'guest')
- Company: ${companyName}
- Current App Route: ${pathname}

Key TeamFlow Domain Knowledge:
- Admin Role: Manages team members, delegates tasks with priorities/categories/deadlines, monitors sprint velocity and aggregated status charts.
- Employee Role: Focuses on execution, views "Next Best Action", accepts deliverables ('new' -> 'active'), marks completed, or documents failed blockers for review.
- Tasks: Have title, category (Frontend, Backend, Database, Security, DevOps, Design, QA), priority (High, Medium, Low), dueDate, status (new, active, completed, failed).

Formatting Instructions:
1. When the user asks to create, draft, design, or generate a task or deliverable spec, you MUST include a JSON code block in the format:
\`\`\`json
{
  "type": "task_draft",
  "title": "Clear concise deliverable title",
  "category": "Frontend | Backend | Database | Security | DevOps",
  "priority": "High | Medium | Low",
  "dueDate": "e.g. In 3 days",
  "description": "2-3 sentences explaining architectural objective and scope",
  "acceptanceCriteria": [
    "Criteria 1",
    "Criteria 2",
    "Criteria 3"
  ]
}
\`\`\`
Followed or preceded by a brief professional note.
2. For all other technical, role, workflow, or architectural queries, provide crisp, senior-dev level markdown with bullet points, bold key terms, and code snippets where relevant. Keep answers concise, actionable, and encouraging.`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${encodeURIComponent(
    GEMINI_API_KEY.trim()
  )}`;

  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      system_instruction: {
        parts: [{ text: systemInstruction }],
      },
      contents: [
        {
          role: "user",
          parts: [{ text: userPrompt }],
        },
      ],
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 1000,
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Gemini API error ${response.status}: ${errorText}`);
  }

  const data = await response.json();
  const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text || "";

  if (!rawText) {
    throw new Error("Empty response from Gemini API");
  }

  // Check if response contains a task JSON block
  const jsonMatch = rawText.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[1]);
      if (parsed.title || parsed.type === "task_draft") {
        const remainingText = rawText
          .replace(/```(?:json)?\s*[\s\S]*?\s*```/, "")
          .trim();
        return {
          type: "task_draft",
          text:
            remainingText ||
            "Here is the deliverable spec generated by FlowAI via Gemini Flash:",
          task: {
            title: parsed.title || "Engineering Deliverable",
            category: parsed.category || "Development",
            priority: parsed.priority || "Medium",
            dueDate: parsed.dueDate || "Next Sprint",
            description: parsed.description || "",
            acceptanceCriteria: Array.isArray(parsed.acceptanceCriteria)
              ? parsed.acceptanceCriteria
              : [
                  "Verify implementation against unit and integration tests.",
                  "Enforce role-based access control and token validation.",
                  "Submit PR for senior peer review.",
                ],
          },
          action:
            role === "admin"
              ? { label: "Open Task Creator", path: "/admin" }
              : null,
          source: "gemini",
        };
      }
    } catch {
      // JSON parse failed, fall through to regular markdown
    }
  }

  return {
    type: "text",
    text: rawText,
    action:
      role === "admin"
        ? { label: "Open Admin Center", path: "/admin" }
        : role === "employee"
        ? { label: "Go to Deliverables", path: "/employee" }
        : null,
    source: "gemini",
  };
};

/**
 * Knowledge Base & Response Generator for FlowAI Senior Dev Copilot (Fallback)
 */
const generateAIResponse = (userPrompt, pathname, user) => {
  const q = userPrompt.toLowerCase().trim();
  const role = user?.role || "guest";
  const userName = user?.name || "there";

  // 1. Task Generation request
  if (
    q.includes("create task") ||
    q.includes("generate task") ||
    q.includes("draft task") ||
    q.includes("new task") ||
    q.includes("task template")
  ) {
    let title = "Implement Resilient Rate-Limiting & Security Headers";
    let category = "Security";
    let priority = "High";
    let dueDate = "Next Sprint (5 days)";

    if (q.includes("database") || q.includes("postgres") || q.includes("migration") || q.includes("sql")) {
      title = "Execute Zero-Downtime PostgreSQL Schema Migration";
      category = "Database";
      priority = "High";
    } else if (q.includes("frontend") || q.includes("ui") || q.includes("design") || q.includes("react")) {
      title = "Refactor Component Hierarchy & Implement Design System Tokens";
      category = "Frontend";
      priority = "Medium";
    } else if (q.includes("auth") || q.includes("sso") || q.includes("oauth") || q.includes("jwt")) {
      title = "Harden Multi-Tenant SAML/OIDC SSO & Refresh Token Rotation";
      category = "Security";
      priority = "High";
    }

    return {
      type: "task_draft",
      text: `Here is a production-ready deliverable draft with acceptance criteria tailored for engineering velocity:`,
      task: {
        title,
        category,
        priority,
        dueDate,
        description: `Implement hardened architectural standards for ${title.toLowerCase()}. Ensure strict regression testing, telemetry logging, and zero impact on current active sessions.`,
        acceptanceCriteria: [
          "End-to-end integration tests pass with >90% code coverage.",
          "Role-Based Access Control (RBAC) validations enforced on all endpoints.",
          "Audit telemetry logging integrated with structured JSON output.",
          "Peer review approved by at least one Senior Engineer.",
        ],
      },
      action: role === "admin" ? { label: "Open Task Creator", path: "/admin" } : null,
    };
  }

  // 2. Role & Security Questions
  if (
    q.includes("role") ||
    q.includes("permission") ||
    q.includes("security") ||
    q.includes("admin vs") ||
    q.includes("rbac")
  ) {
    return {
      type: "text",
      text: `### 🛡️ TeamFlow Role-Based Access Control (RBAC) Architecture\n\nTeamFlow enforces **strict role segregation** at both the routing layer and JWT authentication boundaries:\n\n* **Admin Role**:\n  - Has full company-wide authority to provision/deactivate team members.\n  - Can delegate tasks with specific priorities, categories, and due dates.\n  - Accesses aggregate productivity analytics, status breakdown charts, and team velocity metrics.\n\n* **Employee Role**:\n  - Focused on execution with zero administrative distraction.\n  - Receives automated **Next Best Action** recommendations.\n  - Can accept deliverables (\`new\` → \`active\`), mark deliverables completed, or document failure blockers for review.\n\nAll JWT claims are validated server-side to guarantee multi-tenant isolation.`,
      action: !user ? { label: "Go to Sign In", path: "/login" } : null,
    };
  }

  // 3. Velocity / Throughput / Bottlenecks
  if (
    q.includes("velocity") ||
    q.includes("analytics") ||
    q.includes("throughput") ||
    q.includes("metric") ||
    q.includes("speed")
  ) {
    return {
      type: "text",
      text: `### 📊 Sprint Velocity & Throughput Strategy\n\nTo maximize team momentum in TeamFlow, consider these senior engineering practices:\n\n1. **Batch Delegate by Category**: Group deliverables (e.g., *Frontend*, *Backend*, *Database*) to minimize context switching for developers.\n2. **Enforce Small Batch Sizes**: Break deliverables into 1-to-2 day tasks rather than multi-week epics for faster verification.\n3. **Monitor the 'Failed / Blocked' Queue**: Tasks flagged as failed provide early warnings of external dependencies or missing specs.\n4. **Review Aggregate Completion Rates**: Aim for an 85–90% on-time sprint completion rate to avoid team burnout while maintaining velocity.`,
      action: role === "admin" ? { label: "View Analytics Tab", path: "/admin" } : null,
    };
  }

  // 4. Employee Guidance ("What should I do next?")
  if (
    q.includes("what should i do") ||
    q.includes("next task") ||
    q.includes("my task") ||
    q.includes("blocker") ||
    q.includes("help me")
  ) {
    if (role === "employee") {
      return {
        type: "text",
        text: `Hey **${userName}**! In your Employee Workspace:\n\n1. Check your **Next Best Action** banner at the top of your dashboard—it highlights your most urgent deliverable.\n2. If you have tasks in the **'New'** queue, click **Accept Task** to transition them into **In Progress**.\n3. Keep your focus on one active task at a time to optimize flow state.\n4. Once verified, click **Complete Task** to submit your work, or use **Failed** to log any blockers or missing credentials for the admin.`,
        action: { label: "Open Deliverable Queue", path: "/employee" },
      };
    } else {
      return {
        type: "text",
        text: `As an Admin, your primary focus should be **clear task delegation** and **unblocking your team**.\n\n* Check your **Tasks** tab to see any deliverables currently flagged as *Failed* or *In Progress*.\n* Head to **Create Task** to assign priority deliverables for the upcoming sprint.\n* Use the **Employees** tab to verify active roster counts.`,
        action: { label: "Open Admin Center", path: "/admin" },
      };
    }
  }

  // 5. Navigation & Setup Questions
  if (
    q.includes("setup") ||
    q.includes("register") ||
    q.includes("company") ||
    q.includes("invite") ||
    q.includes("how to start")
  ) {
    return {
      type: "text",
      text: `### 🚀 TeamFlow Onboarding Roadmap\n\n1. **Create Company Workspace**: Register your organization via \`/register-company\` with company name, admin credentials, and master password.\n2. **Provision Employees**: In your Admin Dashboard, open the **Employees** tab and add your team members.\n3. **Assign Deliverables**: Jump to the **Create Task** tab, select an assignee, set due date and priority, and dispatch!\n4. **Monitor in Real Time**: Watch live stats update as your engineers accept and deliver tasks.`,
      action: !user
        ? { label: "Register Organization", path: "/register-company" }
        : { label: "Go to Employees Tab", path: "/admin" },
    };
  }

  // Default fallback
  return {
    type: "text",
    text: `I'm **FlowAI**, your Senior Dev & Architecture Copilot in TeamFlow.\n\nI can help you with:\n* **Drafting detailed engineering tasks** with acceptance criteria\n* **Analyzing sprint throughput** and velocity bottlenecks\n* **Explaining role-based permissions (RBAC)** and security boundaries\n* **Guiding team members** on deliverable execution and blocker reporting\n\nTry asking: *"Generate a high priority backend task"*, *"How do roles work?"*, or *"How to increase team velocity?"*`,
    action: null,
  };
};

/**
 * Floating AI Assistant Component
 */
const AIAssistant = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { user } = useAuth();

  const [isOpen, setIsOpen] = useState(false);
  const [isMinimized, setIsMinimized] = useState(false);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState(null);
  const [showNotification, setShowNotification] = useState(true);

  // Session storage backed message history
  const [messages, setMessages] = useState(() => {
    try {
      const saved = sessionStorage.getItem("flowai_messages");
      if (saved) return JSON.parse(saved);
    } catch {
      // ignore
    }
    return [
      {
        id: "welcome",
        sender: "ai",
        text: `👋 Greetings! I'm **FlowAI**, your workspace copilot. How can I help optimize your team's velocity today?`,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      },
    ];
  });

  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  // Save messages to session storage
  useEffect(() => {
    try {
      sessionStorage.setItem("flowai_messages", JSON.stringify(messages));
    } catch {
      // ignore
    }
  }, [messages]);

  // Scroll to bottom on new message
  useEffect(() => {
    if (isOpen && !isMinimized) {
      messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages, isOpen, isMinimized, isTyping]);

  // Keyboard shortcut: Cmd/Ctrl + K to toggle
  useEffect(() => {
    const handleKeyDown = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setIsOpen((prev) => !prev);
        setIsMinimized(false);
      } else if (e.key === "Escape" && isOpen) {
        setIsOpen(false);
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen]);

  // Focus input when opened
  useEffect(() => {
    if (isOpen && !isMinimized) {
      setTimeout(() => inputRef.current?.focus(), 150);
    }
  }, [isOpen, isMinimized]);

  // Dismiss proactive notification after 9s
  useEffect(() => {
    const timer = setTimeout(() => setShowNotification(false), 9000);
    return () => clearTimeout(timer);
  }, []);

  // Contextual quick suggestions based on current pathname & role
  const quickSuggestions = useMemo(() => {
    const p = location.pathname;
    if (p.includes("/admin")) {
      return [
        "Draft High-Priority Backend Task",
        "How to optimize sprint velocity?",
        "Explain RBAC security boundaries",
      ];
    } else if (p.includes("/employee")) {
      return [
        "What should I work on next?",
        "How to report a task blocker?",
        "Explain sprint velocity metrics",
      ];
    } else {
      return [
        "How does role security work?",
        "Draft a sample engineering task",
        "Guide me through workspace setup",
      ];
    }
  }, [location.pathname]);

  const handleSendMessage = async (textToSend = input) => {
    const prompt = textToSend.trim();
    if (!prompt || isTyping) return;

    const userMessage = {
      id: Date.now().toString(),
      sender: "user",
      text: prompt,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsTyping(true);

    try {
      const responseData = await callGeminiAPI(prompt, location.pathname, user);
      const aiMessage = {
        id: (Date.now() + 1).toString(),
        sender: "ai",
        ...responseData,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };
      setMessages((prev) => [...prev, aiMessage]);
    } catch (err) {
      console.warn("FlowAI: Gemini API call failed, falling back to local engine:", err);
      const fallbackData = generateAIResponse(prompt, location.pathname, user);
      const aiMessage = {
        id: (Date.now() + 1).toString(),
        sender: "ai",
        ...fallbackData,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };
      setMessages((prev) => [...prev, aiMessage]);
    } finally {
      setIsTyping(false);
    }
  };

  const handleCopyTask = (task, index) => {
    const formatted = `TITLE: ${task.title}\nCATEGORY: ${task.category}\nPRIORITY: ${task.priority}\nDUE: ${task.dueDate}\n\nDESCRIPTION:\n${task.description}\n\nACCEPTANCE CRITERIA:\n${task.acceptanceCriteria.map((c) => `- ${c}`).join("\n")}`;
    navigator.clipboard.writeText(formatted);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2500);
  };

  const handleResetChat = () => {
    const initial = [
      {
        id: Date.now().toString(),
        sender: "ai",
        text: `Chat reset. Ready with fresh context for **${location.pathname}**. What would you like to build or orchestrate?`,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      },
    ];
    setMessages(initial);
  };

  // Helper to format basic markdown-style bold and lists
  const renderFormattedText = (rawText) => {
    if (!rawText) return null;
    const lines = rawText.split("\n");
    return lines.map((line, idx) => {
      if (line.startsWith("### ")) {
        return (
          <h4 key={idx} className="font-bold text-[#101827] text-xs sm:text-sm mt-2 mb-1">
            {line.replace("### ", "")}
          </h4>
        );
      }
      if (line.startsWith("* ") || line.startsWith("- ")) {
        return (
          <li key={idx} className="ml-4 text-xs text-[#334155] list-disc my-0.5">
            <span
              dangerouslySetInnerHTML={{
                __html: line
                  .slice(2)
                  .replace(/\*\*(.*?)\*\*/g, '<strong class="text-[#101827] font-semibold">$1</strong>')
                  .replace(/`([^`]+)`/g, '<code class="px-1 py-0.5 rounded bg-[#F1F5F9] text-[#4F46E5] font-mono text-[11px]">$1</code>'),
              }}
            />
          </li>
        );
      }
      if (/^\d+\.\s/.test(line)) {
        return (
          <div key={idx} className="ml-2 text-xs text-[#334155] my-0.5">
            <span
              dangerouslySetInnerHTML={{
                __html: line
                  .replace(/\*\*(.*?)\*\*/g, '<strong class="text-[#101827] font-semibold">$1</strong>')
                  .replace(/`([^`]+)`/g, '<code class="px-1 py-0.5 rounded bg-[#F1F5F9] text-[#4F46E5] font-mono text-[11px]">$1</code>'),
              }}
            />
          </div>
        );
      }
      if (!line.trim()) {
        return <div key={idx} className="h-1.5" />;
      }
      return (
        <p
          key={idx}
          className="text-xs text-[#334155] leading-relaxed my-0.5"
          dangerouslySetInnerHTML={{
            __html: line
              .replace(/\*\*(.*?)\*\*/g, '<strong class="text-[#101827] font-semibold">$1</strong>')
              .replace(/`([^`]+)`/g, '<code class="px-1 py-0.5 rounded bg-[#F1F5F9] text-[#4F46E5] font-mono text-[11px]">$1</code>'),
          }}
        />
      );
    });
  };

  const getContextBadge = () => {
    const p = location.pathname;
    if (p.includes("/admin")) return { label: "Admin Center", color: "text-[#4F46E5] bg-[#EEF2FF] border-[#C7D2FE]" };
    if (p.includes("/employee")) return { label: "Employee Queue", color: "text-[#0284C7] bg-[#F0F9FF] border-[#BAE6FD]" };
    if (p.includes("/login") || p.includes("/signup")) return { label: "Auth Portal", color: "text-[#D97706] bg-[#FFFBEB] border-[#FDE68A]" };
    return { label: "Overview", color: "text-[#64748B] bg-[#F8FAFC] border-[#E2E8F0]" };
  };

  const currentBadge = getContextBadge();

  return (
    <div className="fixed bottom-5 right-5 z-50 select-none">
      {/* ─── Proactive Thought Bubble ─── */}
      {!isOpen && showNotification && (
        <div className="hidden sm:flex items-center gap-3 absolute bottom-16 right-0 mb-2 bg-white p-3.5 rounded-2xl border border-[#E1E5E9] shadow-xl max-w-xs animate-toast-enter">
          <div className="w-8 h-8 rounded-xl bg-[#101827] flex items-center justify-center text-white shrink-0 shadow-sm">
            <Bot className="w-4 h-4" />
          </div>
          <div className="text-left">
            <div className="text-[11px] font-bold text-[#101827] flex items-center gap-1.5">
              FlowAI Copilot
              <span className="w-1.5 h-1.5 rounded-full bg-[#10B981] animate-pulse" />
            </div>
            <p className="text-[10px] text-[#64748B] leading-tight mt-0.5">
              Need assistance delegating tasks or navigating? Press{" "}
              <kbd className="px-1 py-0.5 rounded bg-[#F1F5F9] border border-[#E1E5E9] text-[#475569] font-mono text-[9px]">
                ⌘K
              </kbd>
            </p>
          </div>
          <button
            onClick={() => setShowNotification(false)}
            className="text-[#94A3B8] hover:text-[#101827] p-1 ml-1"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {/* ─── Floating Circular Trigger Button ─── */}
      {!isOpen && (
        <button
          onClick={() => {
            setIsOpen(true);
            setIsMinimized(false);
            setShowNotification(false);
          }}
          className="relative group p-3.5 rounded-2xl bg-[#101827] hover:bg-[#1E293B] text-white shadow-xl hover:shadow-2xl hover:scale-105 active:scale-95 transition-all duration-300 flex items-center gap-2.5 cursor-pointer border border-[#1E293B]"
          aria-label="Open AI Assistant"
        >
          {/* Pulsing Beacon */}
          <span className="absolute -top-1 -right-1 flex h-3 w-3">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#10B981] opacity-75" />
            <span className="relative inline-flex rounded-full h-3 w-3 bg-[#10B981] border-2 border-white" />
          </span>

          <Bot className="w-5 h-5 text-white" />
          <span className="text-xs font-bold tracking-tight pr-1 hidden sm:inline">
            FlowAI
          </span>
          <span className="hidden sm:inline-block px-1.5 py-0.5 rounded-md bg-white/15 text-[10px] font-mono text-white/90">
            ⌘K
          </span>
        </button>
      )}

      {/* ─── Expanded AI Chat Modal ─── */}
      {isOpen && (
        <div
          className={`bg-white border border-[#E1E5E9] shadow-2xl rounded-2xl overflow-hidden transition-all duration-300 flex flex-col ${
            isMinimized
              ? "w-80 h-14"
              : "w-[92vw] sm:w-110 h-145 max-h-[86vh]"
          }`}
        >
          {/* Header Bar */}
          <div className="flex items-center justify-between px-4 py-3 bg-[#101827] text-white shrink-0">
            <div className="flex items-center gap-2.5">
              <div className="relative">
                <div className="w-8 h-8 rounded-xl bg-white/10 flex items-center justify-center text-white">
                  <Bot className="w-4 h-4" />
                </div>
                <span className="absolute -bottom-0.5 -right-0.5 w-2 h-2 rounded-full bg-[#10B981] border border-[#101827]" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="font-bold text-white text-xs sm:text-sm leading-none">
                    FlowAI Copilot
                  </h3>
                  <span
                    className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${currentBadge.color}`}
                  >
                    {currentBadge.label}
                  </span>
                </div>
                <span className="text-[10px] text-[#94A3B8] flex items-center gap-1.5">
                  Senior Dev Copilot
                  <span className="text-[9px] text-[#A5B4FC] font-semibold flex items-center gap-0.5">
                    • <Sparkles className="w-2.5 h-2.5 text-[#A5B4FC] inline" /> Gemini Flash
                  </span>
                </span>
              </div>
            </div>

            <div className="flex items-center gap-1 text-[#94A3B8]">
              <button
                onClick={handleResetChat}
                title="Reset Conversation"
                className="p-1.5 rounded-lg hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
              >
                <RotateCcw className="w-3.5 h-3.5" />
              </button>
              <button
                onClick={() => setIsMinimized((prev) => !prev)}
                title={isMinimized ? "Expand" : "Minimize"}
                className="p-1.5 rounded-lg hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
              >
                {isMinimized ? (
                  <Maximize2 className="w-3.5 h-3.5" />
                ) : (
                  <Minimize2 className="w-3.5 h-3.5" />
                )}
              </button>
              <button
                onClick={() => setIsOpen(false)}
                title="Close (Esc)"
                className="p-1.5 rounded-lg hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Body Content */}
          {!isMinimized && (
            <>
              {/* Message Feed */}
              <div className="flex-1 overflow-y-auto p-4 space-y-4 text-left bg-[#F8FAFC]">
                {messages.map((msg, idx) => (
                  <div
                    key={msg.id || idx}
                    className={`flex flex-col ${
                      msg.sender === "user" ? "items-end" : "items-start"
                    }`}
                  >
                    <div
                      className={`max-w-[88%] rounded-2xl px-3.5 py-2.5 text-xs shadow-xs ${
                        msg.sender === "user"
                          ? "bg-[#101827] text-white rounded-tr-xs"
                          : "bg-white border border-[#E1E5E9] text-[#1E293B] rounded-tl-xs"
                      }`}
                    >
                      {msg.sender === "ai" ? (
                        renderFormattedText(msg.text)
                      ) : (
                        <p className="leading-relaxed whitespace-pre-wrap">{msg.text}</p>
                      )}

                      {/* Structured Task Draft Card */}
                      {msg.type === "task_draft" && msg.task && (
                        <div className="mt-3 p-3.5 rounded-xl bg-[#F1F5F9] border border-[#CBD5E1] text-left space-y-2">
                          <div className="flex items-center justify-between">
                            <span className="text-[10px] uppercase font-bold text-[#D97706]">
                              {msg.task.priority} Priority · {msg.task.category}
                            </span>
                            <span className="text-[10px] text-[#64748B]">
                              Due: {msg.task.dueDate}
                            </span>
                          </div>

                          <div className="font-bold text-[#101827] text-xs">
                            {msg.task.title}
                          </div>

                          <p className="text-[11px] text-[#475569] leading-snug">
                            {msg.task.description}
                          </p>

                          {msg.task.acceptanceCriteria && (
                            <div className="pt-2 border-t border-[#E2E8F0]">
                              <span className="text-[10px] uppercase font-bold text-[#64748B] block mb-1">
                                Acceptance Criteria
                              </span>
                              <ul className="space-y-1">
                                {msg.task.acceptanceCriteria.map((c, i) => (
                                  <li
                                    key={i}
                                    className="text-[10px] text-[#334155] flex items-start gap-1.5"
                                  >
                                    <Check className="w-3 h-3 text-[#059669] shrink-0 mt-0.5" />
                                    <span>{c}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}

                          <button
                            onClick={() => handleCopyTask(msg.task, idx)}
                            className="w-full mt-2 py-1.5 px-3 rounded-lg bg-white hover:bg-[#F8FAFC] border border-[#CBD5E1] text-[#101827] text-[11px] font-semibold flex items-center justify-center gap-1.5 transition-colors cursor-pointer shadow-xs"
                          >
                            {copiedIndex === idx ? (
                              <>
                                <CheckCircle2 className="w-3.5 h-3.5 text-[#059669]" />
                                <span>Copied Spec to Clipboard!</span>
                              </>
                            ) : (
                              <>
                                <Copy className="w-3.5 h-3.5 text-[#64748B]" />
                                <span>Copy Deliverable Spec</span>
                              </>
                            )}
                          </button>
                        </div>
                      )}

                      {/* Optional Context Action Link */}
                      {msg.action && (
                        <div className="mt-2.5 pt-2 border-t border-[#E1E5E9]">
                          <button
                            onClick={() => {
                              navigate(msg.action.path);
                              setIsOpen(false);
                            }}
                            className="inline-flex items-center gap-1.5 text-[11px] font-bold text-[#4F46E5] hover:text-[#4338CA] transition-colors cursor-pointer"
                          >
                            <span>{msg.action.label}</span>
                            <ArrowRight className="w-3 h-3" />
                          </button>
                        </div>
                      )}
                    </div>

                    <span className="text-[9px] text-[#94A3B8] mt-1 px-1">
                      {msg.timestamp}
                    </span>
                  </div>
                ))}

                {/* Live Typing Indicator */}
                {isTyping && (
                  <div className="flex items-center gap-2 p-2.5 rounded-xl bg-white border border-[#E1E5E9] w-20 shadow-xs">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#4F46E5] animate-bounce" />
                    <span
                      className="w-1.5 h-1.5 rounded-full bg-[#6366F1] animate-bounce"
                      style={{ animationDelay: "150ms" }}
                    />
                    <span
                      className="w-1.5 h-1.5 rounded-full bg-[#818CF8] animate-bounce"
                      style={{ animationDelay: "300ms" }}
                    />
                  </div>
                )}
                <div ref={messagesEndRef} />
              </div>

              {/* Quick Suggestions Chips */}
              <div className="px-3 py-2 bg-white border-t border-[#E1E5E9] flex items-center gap-1.5 overflow-x-auto">
                <Lightbulb className="w-3.5 h-3.5 text-[#F59E0B] shrink-0 ml-1" />
                {quickSuggestions.map((suggestion, i) => (
                  <button
                    key={i}
                    onClick={() => handleSendMessage(suggestion)}
                    className="whitespace-nowrap px-2.5 py-1 rounded-full bg-[#F1F5F9] hover:bg-[#E2E8F0] border border-[#E1E5E9] text-[#475569] hover:text-[#101827] text-[10px] font-medium transition-colors cursor-pointer shrink-0"
                  >
                    {suggestion}
                  </button>
                ))}
              </div>

              {/* Input Bar */}
              <div className="p-3 bg-white border-t border-[#E1E5E9]">
                <form
                  onSubmit={(e) => {
                    e.preventDefault();
                    handleSendMessage();
                  }}
                  className="flex items-center gap-2"
                >
                  <input
                    ref={inputRef}
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder="Ask FlowAI or request a task spec..."
                    className="flex-1 bg-white border border-[#E1E5E9] focus:border-[#4F46E5] focus:ring-1 focus:ring-[#4F46E5] px-3.5 py-2.5 rounded-xl text-xs text-[#101827] placeholder-[#94A3B8] focus:outline-none transition-all"
                  />
                  <button
                    type="submit"
                    disabled={!input.trim() || isTyping}
                    className="p-2.5 rounded-xl bg-[#101827] hover:bg-[#1E293B] text-white disabled:opacity-40 disabled:cursor-not-allowed shadow-xs cursor-pointer transition-transform active:scale-95 shrink-0"
                    aria-label="Send query"
                  >
                    <Send className="w-4 h-4" />
                  </button>
                </form>
                <div className="flex items-center justify-between text-[9px] text-[#94A3B8] mt-1.5 px-1">
                  <span>Context-aware for {user?.name ? `${user.name} (${user.role})` : "Guest"}</span>
                  <span>Esc to close</span>
                </div>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
};

export default AIAssistant;
